Extract Issue Id and update project custom field

diff --git a/.github/workflows/PullRequestReviewResult.yml b/.github/workflows/PullRequestReviewResult.yml
--- a/.github/workflows/PullRequestReviewResult.yml
+++ b/.github/workflows/PullRequestReviewResult.yml
@@ -26,7 +26,26 @@ jobs:
             exit 1
           fi
 
-      - name: Update Project Custom Field
+      - name: Extract Issue Id from Issue No
+        id: get_issue_id
+        run: |
+          gh api graphql -F owner='Tokuisaki-Ankenmei001' -F repo='Sample-Common' -F number=${{ steps.get_issue_number.outputs.issue_number }} -f query='
+
+          orga='Tokuisaki-Ankenmei001'
+          repo='Sample-Common'
+          numb=${{ steps.get_issue_number.outputs.issue_number }}
+          QUERY='query($orga: String!, $repo: String!, $numb: Int!) { repository(owner: $orga, name: $repo) { issue(number: $numb) { id projectItems(first:20) { nodes { id } } } } } '
+          RESPONSE=$(gh api graphql -f query="$QUERY" --jq '.data.repository.issue.projectItems.nodes.id'
+          ISSUE_GLOBAL_ID=$RESPONSE
+          if [ -n "$ISSUE_GLOBAL_ID" ]; then
+            echo "issue_global_id=$ISSUE_GLOBAL_ID" >> $GITHUB_OUTPUT
+            echo "Found Issue Id: $ISSUE_GLOBAL_ID"
+          else
+            echo "::error::No Issue Id from Issue No. Please link an issue (e.g., #123)."
+            exit 1
+          fi
+
+      - name: Set Project Custom FieldId
         id: get_status
         run: |
           if ${{ github.event.review.state == 'approved' }}; then
@@ -48,12 +67,6 @@ jobs:
         if: ${{ steps.get_issue_number.outputs.issue_number != '' }} && ${{ steps.get_status.outputs.issue_status != '' }}
         env:
           GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
-          # 環境変数で必要な情報を定義
-          ORG: ${{ github.repository_owner }} # 組織名 (組織プロジェクトの場合)
-          PROJECT_NUMBER: 3 # プロジェクト番号
-          FIELD_NAME: "Status" # 更新したいカスタムフィールド名
-          NEW_VALUE: ${{ steps.get_status.outputs.issue_status }} # 設定したい値
-          ISSUE_NUMBER: ${{ steps.get_issue_number.outputs.issue_number }}
 
         run: |
-          gh project item-edit --id 'PVTI_lADODp9rL84BJGxGzgie9yU' --field-id 'PVTSSF_lADODp9rL84BJGxGzg5XjHw' --project-id 'PVT_kwDODp9rL84BJGxG' --single-select-option-id '${{ steps.get_status.outputs.issue_status }}'
+          gh project item-edit --id '${{ steps.get_issue_id.outputs.issue_global_id }}' --field-id 'PVTSSF_lADODp9rL84BJGxGzg5XjHw' --project-id 'PVT_kwDODp9rL84BJGxG' --single-select-option-id '${{ steps.get_status.outputs.issue_status }}'
