Refactor GitHub Actions workflow for PR reviews

diff --git a/.github/workflows/PullRequestReviewResult.yml b/.github/workflows/PullRequestReviewResult.yml
--- a/.github/workflows/PullRequestReviewResult.yml
+++ b/.github/workflows/PullRequestReviewResult.yml
@@ -10,6 +10,7 @@ jobs:
     # レビューのタイプが 'approved'、'changes_requested' の場合にのみ実行
     if: ${{ github.event.review.state == 'approved' || github.event.review.state == 'changes_requested' }}
     steps:
+      # プルリクエスト本文からIssue番号を抽出
       - name: Extract Issue number from PR body
         id: get_issue_number
         run: |
@@ -23,7 +24,7 @@ jobs:
             echo "::error::No Issue NUMBER found in PR body. Please link an issue (e.g., #123)."
             exit 1
           fi
-
+      # Issue番号からIssueのグローバルIDを抽出
       - name: Extract Issue Id from Issue No
         id: get_issue_id
         env:
@@ -42,14 +43,14 @@ jobs:
               }
             }
           '
-          RESPONSE=$(gh api graphql \
-            -F orga="${{ github.repository_owner }}" \
-            -F repo="${{ github.event.repository.name }}" \
-            -F numb=${{ steps.get_issue_number.outputs.issue_number }} \
-            -F query="$GRAPHQL_QUERY" \
+          ISSUEID=$(gh api graphql \
+            -f orga="${{ github.repository_owner }}" \
+            -f repo="${{ github.event.repository.name }}" \
+            -f numb=${{ steps.get_issue_number.outputs.issue_number }} \
+            -f query="$GRAPHQL_QUERY" \
             --jq '.data.repository.issue.projectItems.nodes[0].id // empty'
           )
-          ISSUE_GLOBAL_ID=$RESPONSE
+          ISSUE_GLOBAL_ID=$ISSUEID
           if [ -n "$ISSUE_GLOBAL_ID" ]; then
             echo "issue_global_id=$ISSUE_GLOBAL_ID" >> $GITHUB_OUTPUT
             echo "Found Issue Id: $ISSUE_GLOBAL_ID"
@@ -57,16 +58,158 @@ jobs:
             echo "::error::No Issue Id from Issue No. Please link an issue (e.g., #123)."
             exit 1
           fi
-
-      - name: Set Project Custom FieldId
-        id: get_status
+      # Organization名称とプロジェクト名称からプロジェクトIDを抽出
+      - name: Extract Project Id from Project No
+        id: get_Project_id
+        env:
+          GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
+        run: |
+          PROJECTID_QUERY='
+            query($org: String!) {
+              organization(login: $org) {
+                projectsV2(first: 20) {
+                  nodes {
+                    id
+                    title
+                  }
+                }
+              }
+            }
+          '
+          PROJECTID=$(gh api graphql \
+            -f orga="${{ github.repository_owner }}" \
+            -f query="$PROJECTID_QUERY" \
+            | jq --arg target "@horie-mobile's untitled project" '.data.organization.projectsV2.nodes[] | select(.title == $target) | .id // empty'
+          )
+          PROJECT_ID=$PROJECTID
+          if [ -n "$PROJECT_ID" ]; then
+            echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
+            echo "Found Project Id: $PROJECT_ID"
+          else
+            echo "::error::No Project Id from Project No. Please link an issue (e.g., #123)."
+            exit 1
+          fi
+      # プロジェクトIDからカスタムフィールド「Status」のIDを抽出
+      - name: Extract Custom Field Status Id from Project ID
+        id: get_Status_Field_Id
+        env:
+          GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
+        run: |
+          FIELDID_QUERY='
+            query($id: ID!) {
+              node(id: $id) {
+                ... on ProjectV2 {
+                  fields(first: 20) {
+                    nodes {
+                      ... on ProjectV2SingleSelectField {
+                        name
+                        id
+                      }
+                    }
+                  }
+                }
+              }
+            }
+          '
+          FIELDID=$(gh api graphql \
+            -f pjid=${{ steps.get_Project_id.outputs.project_id }} \
+            -f query="$FIELDID_QUERY" \
+            | jq --arg target "Status" '.data.node.fields.nodes[] | select(.name == $target) | .id // empty'
+          )
+          FIELD_ID=$FIELDID
+          if [ -n "$FIELD_ID" ]; then
+            echo "status_id=$FIELD_ID" >> $GITHUB_OUTPUT
+            echo "Found status Id: $FIELD_ID"
+          else
+            echo "::error::No Status Id from Project No. Please link an issue (e.g., #123)."
+            exit 1
+          fi
+      # プロジェクトIDからカスタムフィールド「Status」のオプション「レビュー否認」のIDを抽出
+      - name: Set Project Custom Field Options Deny Id from
+        id: get_Status_Deny_Id
+        env:
+          GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
+        run: |
+          DENYID_QUERY='
+            query($pjid: ID!) {
+              node(id: $pjid) {
+                ... on ProjectV2 {
+                  fields(first: 20) {
+                    nodes {
+                      ... on ProjectV2SingleSelectField {
+                        id
+                        name
+                        options {
+                          id
+                          name
+                        }
+                      }
+                    }
+                  }
+                }
+              }
+            }
+          '
+          DENYID=$(gh api graphql \
+            -f pjid=${{ steps.get_Project_id.outputs.project_id }} \
+            -f query="$DENYID_QUERY" \
+            --jq '.data.node.fields.nodes[] | select(.name == \"Status\") | .options[] | select(.name == \"レビュー否認\") | .id // empty'
+          )
+          DENY_ID=$DENYID
+          if [ -n "$DENY_ID" ]; then
+            echo "deny_id=$DENY_ID" >> $GITHUB_OUTPUT
+            echo "Found deny Id: $DENY_ID"
+          else
+            echo "::error::No Deny Id from Project No. Please link an issue (e.g., #123)."
+            exit 1
+          fi
+      # プロジェクトIDからカスタムフィールド「Status」のオプション「レビュー承認」のIDを抽出
+      - name: Set Project Custom Field Options Approve Id from
+        id: get_Status_Approve_Id
+        env:
+          GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
+        run: |
+          APPROVEID_QUERY='
+            query($pjid: ID!) {
+              node(id: $pjid) {
+                ... on ProjectV2 {
+                  fields(first: 20) {
+                    nodes {
+                      ... on ProjectV2SingleSelectField {
+                        id
+                        name
+                        options {
+                          id
+                          name
+                        }
+                      }
+                    }
+                  }
+                }
+              }
+            }
+          '
+          APPROVEID=$(gh api graphql \
+            -f pjid=${{ steps.get_Project_id.outputs.project_id }} \
+            -f query="$APPROVEID_QUERY" \
+            --jq '.data.node.fields.nodes[] | select(.name == \"Status\") | .options[] | select(.name == \"レビュー承認\") | .id // empty'
+          )
+          APPROVE_ID=$APPROVEID
+          if [ -n "$APPROVE_ID" ]; then
+            echo "approve_id=$DENY_ID" >> $GITHUB_OUTPUT
+            echo "Found approve Id: $APPROVE_ID"
+          else
+            echo "::error::No Approve Id from Project No. Please link an issue (e.g., #123)."
+            exit 1
+          fi
+      # 実行されたプルリクエストの操作によりレビュー承認・否認のIDを設定
+      - name: Set Project Custom Field Options Id
+        id: set_status
         run: |
           if ${{ github.event.review.state == 'approved' }}; then
-            ISSUE_STATUS="aec7d9c6" # 承認
-          elif ${{ github.event.review.state == 'changes_requested' }}; then
-            ISSUE_STATUS="cd31b70e" # 否認
+            ISSUE_STATUS=${{ steps.get_Status_Approve_Id.outputs.approve_id }} # 承認
           else
-            ISSUE_STATUS="c90d9d31" # 依頼
+            ISSUE_STATUS=${{ steps.get_Status_Deny_Id.outputs.deny_id }} # 否認
           fi
           if [ -n "$ISSUE_STATUS" ]; then
             echo "issue_status=$ISSUE_STATUS" >> $GITHUB_OUTPUT
@@ -81,4 +224,4 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.Sample_My_Secret }}
         run: |
-          gh project item-edit --id '${{ steps.get_issue_id.outputs.issue_global_id }}' --field-id 'PVTSSF_lADODp9rL84BJGxGzg5XjHw' --project-id 'PVT_kwDODp9rL84BJGxG' --single-select-option-id '${{ steps.get_status.outputs.issue_status }}'
+          gh project item-edit --id '${{ steps.get_issue_id.outputs.issue_global_id }}' --field-id '${{ steps.get_Status_Field_Id.outputs.status_id }}' --project-id '${{ steps.get_project_id.outputs.project_id }}' --single-select-option-id '${{ steps.get_status.outputs.issue_status }}
